# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 668da783f111dbc577f5234aaa01db2ae1d3117f5428a00436960fd8a06eb1d75cb75da5a70902a825d02c96928ce73d97c0eb81aa3cf199b7d117a81f70a177
  paypal_host: https://www.sandbox.paypal.com
  app_host: localhost:3000

test:
  secret_key_base: f89da39cf1cd7f83cc08262a9b536bb56fd98dfed3a0449ca6f08f444eaca6cdf672777b9bc79a24538e63c2f50a26cbee00d5479515d1a60343be99ae3fd22a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  paypal_host: https://www.paypal.com
  app_host: https://expresswills.herokuapp.com
